services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - zivgitlab
    ports:
      - "8080:8080"
    environment:
      - ROSETTA_AUTH_FILE=/run/secrets/rosetta-auth
    secrets:
      - rosetta-auth
  swagger_ui: # use docker-image to serve swagger-ui: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#docker
    build:
      context: .
      dockerfile: Dockerfile.swaggerui
      secrets:
        - zivgitlab
    ports:
      - "80:8080"
    environment:
      - BASE_URL=${BASE_URL}
      - SWAGGER_JSON=${SWAGGER_JSON}
secrets:
  zivgitlab:
    file: ~/.netrc
  rosetta-auth:
    file: ~/.rosetta/rosetta_auth
